kernel_list: [1, 3, 5]
batch_size: 64
n_splits: 10
epochs: 2
print_interval: 2000
seed: 1
learning_rate: 1e-3
filter_numbers: [(8, 16), (32, 64), (124, 256)]
kernel_size: [3, 5, 7]
layer_configs: (
    {
        'type':  "conv",
        'in_channels': 1,
        'out_channels': 6,
        'kernel_size': 5,
        'activation': "ReLU",
        'pooling': 2
    },
    {
        'type':  "conv",
        'in_channels': 6,
        'out_channels': 16,
        'kernel_size': 5,
        'activation': "ReLU",
        'pooling': 2
    },
    {
        'type':  "linear",
        'in_features': 16*4*4, #256
        'out_features': 120,
        'activation': "ReLU",
    },
    {
        'type':  "linear",
        'in_features': 120,
        'out_features': 84,
        'activation': "ReLU",
    },
    {
        'type':  "linear",
        'in_features': 84,
        'out_features': 10,
    }
)