seed: 1
model_type: logreg
batch_size: 64
n_splits: 5
print_interval: 2000
# Learning rate values to test
learning_rates: [0.00001,0.0001,0.001, 0.01, 0.1]

# Batch size values to test
batch_sizes: [16, 32, 64, 128, 256]

# Number of epochs to test
epochs_list: [5, 10, 15, 20, 25]

