grid_search: kernel+filter 
save_results: False 
save_plot: False
model_type: cnn
filter_number: [[8, 16], [16, 32], [32, 64]] 
kernel_size: [3, 5, 7]
batch_size: 64
n_splits: 5
epochs: 10
learning_rate: 0.001 
print_interval: 500
seed: 1
save_path: /results/cnn_grid_search


