grid_search: dropout_vs_activations
save_results: True
save_plot: False
model_type: cnn
batch_size: 64
n_splits: 5
epochs: 20
learning_rate: 0.001
kernel_size: 5 
filter_number: [32, 64]
print_interval: 2000
seed: 1
save_path: /results/cnn_grid_search
pooling: 2
# Grid search values
dropout_rate: [0.3, 0.4, 0.5]
activation_function: ['ReLU', 'Leaky ReLU']