grid_search: padding_vs_pooling # This file was used dec 13, do not change before delivery
save_results: True
save_plot: True 
model_type: cnn
batch_size: 64
n_splits: 5
epochs: 10
learning_rate: 0.001
kernel_size: 5 
filter_number: [32, 64]
print_interval: 2000
seed: 1
save_path: /results/cnn_grid_search
pooling: [0, 2]