grid_search: epochs+lr 
save_results: True
save_plot: True
model_type: cnn
batch_size: 64
n_splits: 5
epochs: [5, 10, 20]
learning_rate: [0.01, 0.001, 0.0001] 
kernel_size: 5 
filter_number: [8, 16] 
print_interval: 2000
seed: 1
save_path: /results/cnn_grid_search


