seed: 1
model_type: logreg
save_plot: True
n_splits: 5
print_interval: 2000

# Fixed values 
learning_rate: 0.1 # The best value from searching learning rates
batch_size: 64 # The best batch size
epochs: 10 # The best number of epoch